=begin
#Pulp 3 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PulpDockerClient::DistributionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DistributionsApi' do
  before do
    # run before each test
    @api_instance = PulpDockerClient::DistributionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DistributionsApi' do
    it 'should create an instance of DistributionsApi' do
      expect(@api_instance).to be_instance_of(PulpDockerClient::DistributionsApi)
    end
  end

  # unit tests for distributions_docker_docker_create
  # Create a docker distribution
  # Trigger an asynchronous create task
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'distributions_docker_docker_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for distributions_docker_docker_delete
  # Delete a docker distribution
  # Trigger an asynchronous delete task
  # @param docker_distribution_href URI of Docker Distribution. e.g.: /pulp/api/v3/distributions/docker/docker/1/
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'distributions_docker_docker_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for distributions_docker_docker_list
  # List docker distributions
  # ViewSet for DockerDistribution model.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :name__in Filter results where name is in a comma-separated list of values
  # @option opts [String] :base_path 
  # @option opts [String] :base_path__contains Filter results where base_path contains value
  # @option opts [String] :base_path__icontains Filter results where base_path contains value
  # @option opts [String] :base_path__in Filter results where base_path is in a comma-separated list of values
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @return [InlineResponse2005]
  describe 'distributions_docker_docker_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for distributions_docker_docker_partial_update
  # Partially update a docker distribution
  # Trigger an asynchronous partial update task
  # @param docker_distribution_href URI of Docker Distribution. e.g.: /pulp/api/v3/distributions/docker/docker/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'distributions_docker_docker_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for distributions_docker_docker_read
  # Inspect a docker distribution
  # ViewSet for DockerDistribution model.
  # @param docker_distribution_href URI of Docker Distribution. e.g.: /pulp/api/v3/distributions/docker/docker/1/
  # @param [Hash] opts the optional parameters
  # @return [DockerDistribution]
  describe 'distributions_docker_docker_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for distributions_docker_docker_update
  # Update a docker distribution
  # Trigger an asynchronous update task
  # @param docker_distribution_href URI of Docker Distribution. e.g.: /pulp/api/v3/distributions/docker/docker/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'distributions_docker_docker_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
