=begin
#Pulp 3 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

# Common files
require 'pulp_docker_client/api_client'
require 'pulp_docker_client/api_error'
require 'pulp_docker_client/version'
require 'pulp_docker_client/configuration'

# Models
require 'pulp_docker_client/models/async_operation_response'
require 'pulp_docker_client/models/blob'
require 'pulp_docker_client/models/docker_distribution'
require 'pulp_docker_client/models/docker_remote'
require 'pulp_docker_client/models/inline_response200'
require 'pulp_docker_client/models/inline_response2001'
require 'pulp_docker_client/models/inline_response2002'
require 'pulp_docker_client/models/inline_response2003'
require 'pulp_docker_client/models/inline_response2004'
require 'pulp_docker_client/models/inline_response2005'
require 'pulp_docker_client/models/inline_response2006'
require 'pulp_docker_client/models/manifest'
require 'pulp_docker_client/models/manifest_list'
require 'pulp_docker_client/models/manifest_list_tag'
require 'pulp_docker_client/models/manifest_tag'
require 'pulp_docker_client/models/repository_sync_url'

# APIs
require 'pulp_docker_client/api/content_api'
require 'pulp_docker_client/api/distributions_api'
require 'pulp_docker_client/api/remotes_api'

module PulpDockerClient
  class << self
    # Customize default settings for the SDK using block.
    #   PulpDockerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
