=begin
#Pulp 3 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'date'

module PulpDockerClient
  class DockerDistribution
    # The base (relative) path component of the published url. Avoid paths that                     overlap with other distribution base paths (e.g. \"foo\" and \"foo/bar\")
    attr_accessor :base_path

    # A unique name. Ex, `rawhide` and `stable`.
    attr_accessor :name

    # The latest RepositoryVersion for this Repository will be served.
    attr_accessor :repository

    attr_accessor :_href

    # An optional content-guard.
    attr_accessor :content_guard

    # Timestamp of creation.
    attr_accessor :_created

    # RepositoryVersion to be served
    attr_accessor :repository_version

    # The Registry hostame:port/name/ to use with docker pull command defined by this distribution.
    attr_accessor :registry_path

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'base_path' => :'base_path',
        :'name' => :'name',
        :'repository' => :'repository',
        :'_href' => :'_href',
        :'content_guard' => :'content_guard',
        :'_created' => :'_created',
        :'repository_version' => :'repository_version',
        :'registry_path' => :'registry_path'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'base_path' => :'String',
        :'name' => :'String',
        :'repository' => :'String',
        :'_href' => :'String',
        :'content_guard' => :'String',
        :'_created' => :'DateTime',
        :'repository_version' => :'String',
        :'registry_path' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PulpDockerClient::DockerDistribution` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PulpDockerClient::DockerDistribution`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'base_path')
        self.base_path = attributes[:'base_path']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'repository')
        self.repository = attributes[:'repository']
      end

      if attributes.key?(:'_href')
        self._href = attributes[:'_href']
      end

      if attributes.key?(:'content_guard')
        self.content_guard = attributes[:'content_guard']
      end

      if attributes.key?(:'_created')
        self._created = attributes[:'_created']
      end

      if attributes.key?(:'repository_version')
        self.repository_version = attributes[:'repository_version']
      end

      if attributes.key?(:'registry_path')
        self.registry_path = attributes[:'registry_path']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @base_path.nil?
        invalid_properties.push('invalid value for "base_path", base_path cannot be nil.')
      end

      if @base_path.to_s.length > 255
        invalid_properties.push('invalid value for "base_path", the character length must be smaller than or equal to 255.')
      end

      if @base_path.to_s.length < 1
        invalid_properties.push('invalid value for "base_path", the character length must be great than or equal to 1.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 255
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 255.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be great than or equal to 1.')
      end

      if !@registry_path.nil? && @registry_path.to_s.length < 1
        invalid_properties.push('invalid value for "registry_path", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @base_path.nil?
      return false if @base_path.to_s.length > 255
      return false if @base_path.to_s.length < 1
      return false if @name.nil?
      return false if @name.to_s.length > 255
      return false if @name.to_s.length < 1
      return false if !@registry_path.nil? && @registry_path.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] base_path Value to be assigned
    def base_path=(base_path)
      if base_path.nil?
        fail ArgumentError, 'base_path cannot be nil'
      end

      if base_path.to_s.length > 255
        fail ArgumentError, 'invalid value for "base_path", the character length must be smaller than or equal to 255.'
      end

      if base_path.to_s.length < 1
        fail ArgumentError, 'invalid value for "base_path", the character length must be great than or equal to 1.'
      end

      @base_path = base_path
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 255
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 255.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be great than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] registry_path Value to be assigned
    def registry_path=(registry_path)
      if !registry_path.nil? && registry_path.to_s.length < 1
        fail ArgumentError, 'invalid value for "registry_path", the character length must be great than or equal to 1.'
      end

      @registry_path = registry_path
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          base_path == o.base_path &&
          name == o.name &&
          repository == o.repository &&
          _href == o._href &&
          content_guard == o.content_guard &&
          _created == o._created &&
          repository_version == o.repository_version &&
          registry_path == o.registry_path
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [base_path, name, repository, _href, content_guard, _created, repository_version, registry_path].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        PulpDockerClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
